import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/app/components/layout/Header'
import Footer from '@/app/components/layout/footer'
import Providers from '@/components/ui/Provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <Providers>
      <body className={inter.className} >
      <Header/>
      <div className='px-28'> {children} </div>
      </body>
      <Footer/>
      </Providers>
     
    </html>
  )
}
